#Jekyll
title:          Melrose Designs
name:           melrosedesignco
url:            http://melrosedesignco.com
year:           2016

#Assets
sass:
    sass_dir:   _sass
    style:      :compressed

#Destination
destination: "_site"

#Exclude
exclude: ["node_modules", ".git", ".sass-cache", ".gitignore", "CNAME", "gruntfile.js", "package.json", "readme.md", "server.js"]
